In [25]:
import torch
import torchvision

ModuleNotFoundError: No module named 'torchvision'

In [4]:
tensor = torch.rand(7, 7)
tensor

tensor([[0.4705, 0.8217, 0.3335, 0.0944, 0.6985, 0.3395, 0.6916],
        [0.5692, 0.4288, 0.5709, 0.0407, 0.1896, 0.4214, 0.8887],
        [0.7961, 0.2991, 0.6907, 0.1725, 0.8162, 0.2427, 0.9704],
        [0.9939, 0.8292, 0.7694, 0.8932, 0.2172, 0.7616, 0.6925],
        [0.4203, 0.1232, 0.7273, 0.4145, 0.8386, 0.2964, 0.4710],
        [0.7717, 0.2229, 0.4849, 0.2393, 0.8513, 0.9274, 0.7401],
        [0.8835, 0.9421, 0.2709, 0.4120, 0.3016, 0.6524, 0.1113]])

In [6]:
tensor.mm(torch.rand(1, 7).T)

tensor([[1.9324],
        [1.7186],
        [2.3622],
        [2.2213],
        [1.6925],
        [2.4715],
        [1.5907]])

In [8]:
torch.manual_seed(0)
tensor = torch.rand(7, 7)
torch.manual_seed(0)
tesnor1 = torch.rand(1, 7)
tensor, tesnor1

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]))

In [9]:
tensor.min()

tensor(0.0223)

In [13]:
tensor.argmax()

tensor(26)

In [15]:
tensor = torch.rand(1, 1, 1, 10)
tensor.size()

torch.Size([1, 1, 1, 10])

In [16]:
new_tensor = torch.squeeze(tensor, dim=0)
new_tensor = torch.squeeze(new_tensor, dim=0)
new_tensor = torch.squeeze(new_tensor, dim=0)
new_tensor.size()

torch.Size([10])

In [19]:
new_tensor.shape

torch.Size([10])

In [21]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
print(tensor),  print(tensor.size())
torch.manual_seed(7)
new_tensor = torch.squeeze(tensor, dim=0)
new_tensor = torch.squeeze(new_tensor, dim=0)
new_tensor = torch.squeeze(new_tensor, dim=0)
new_tensor, new_tensor.size()

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

In [23]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
